#############################################################################
# Makefile for building: DataRanking
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  DataRanking.pro
# Template: subdirs
# Command: /Users/arkygeek/dev/qt5/qtbase/bin/qmake -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile DataRanking.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /Users/arkygeek/dev/qt5/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-gui \
		sub-RankPointGenerator \
		sub-ModelDetails


sub-gui-qmake_all:  FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd gui/ && $(MAKE) -f Makefile qmake_all
sub-gui: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-gui-make_first: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-gui-all: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-gui-clean: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-gui-distclean: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-gui-install_subtargets: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-gui-uninstall_subtargets: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-RankPointGenerator-qmake_all:  FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd RankPointGenerator/ && $(MAKE) -f Makefile qmake_all
sub-RankPointGenerator: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-RankPointGenerator-make_first: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-RankPointGenerator-all: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-RankPointGenerator-clean: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-RankPointGenerator-distclean: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-RankPointGenerator-install_subtargets: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-RankPointGenerator-uninstall_subtargets: FORCE
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ModelDetails-qmake_all:  FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd ModelDetails/ && $(MAKE) -f Makefile qmake_all
sub-ModelDetails: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-ModelDetails-make_first: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ModelDetails-all: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ModelDetails-clean: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ModelDetails-distclean: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ModelDetails-install_subtargets: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ModelDetails-uninstall_subtargets: FORCE
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: DataRanking.pro .qmake.cache /Users/arkygeek/dev/qt5/qtbase/mkspecs/macx-clang/qmake.conf /Users/arkygeek/dev/qt5/qtbase/mkspecs/features/spec_pre.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/qdevice.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/device_config.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/shell-unix.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/unix.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/mac.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/macx.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/gcc-base.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/gcc-base-mac.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/clang.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/clang-mac.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/qconfig.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_core.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_declarative.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designer.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_enginio.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_gui.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_help.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_network.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qml.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quick.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_script.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sql.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_svg.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkit.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xml.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qml.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qml1plugindump.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlbundle.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmljs.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlscene.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_uic.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qt_functions.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qt_config.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/macx-clang/qmake.conf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/exclusive_builds.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/default_pre.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/default_pre.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/resolve_config.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/default_post.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/sdk.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/default_post.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/objective_c.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qml_debug.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/declarative_debug.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/warn_on.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/rez.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/testcase_targets.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/exceptions.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/yacc.prf \
		/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/lex.prf \
		DataRanking.pro
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile DataRanking.pro
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/spec_pre.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/qdevice.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/device_config.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/shell-unix.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/unix.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/mac.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/macx.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/gcc-base.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/gcc-base-mac.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/clang.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/common/clang-mac.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/qconfig.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_core.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_declarative.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designer.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_enginio.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_gui.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_help.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_network.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qml.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quick.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_script.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sql.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_svg.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkit.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xml.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qdoc.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qml.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qml1plugindump.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlbundle.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmljs.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmlscene.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_uic.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qt_functions.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qt_config.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/macx-clang/qmake.conf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/spec_post.prf:
.qmake.cache:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/exclusive_builds.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/default_pre.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/default_pre.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/resolve_config.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/default_post.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/sdk.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/default_post.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/objective_c.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/qml_debug.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/declarative_debug.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/warn_on.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/mac/rez.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/testcase_targets.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/exceptions.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/yacc.prf:
/Users/arkygeek/dev/qt5/qtbase/mkspecs/features/lex.prf:
DataRanking.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile DataRanking.pro

qmake_all: sub-gui-qmake_all sub-RankPointGenerator-qmake_all sub-ModelDetails-qmake_all FORCE

make_first: sub-gui-make_first sub-RankPointGenerator-make_first sub-ModelDetails-make_first FORCE
all: sub-gui-all sub-RankPointGenerator-all sub-ModelDetails-all FORCE
clean: sub-gui-clean sub-RankPointGenerator-clean sub-ModelDetails-clean FORCE
distclean: sub-gui-distclean sub-RankPointGenerator-distclean sub-ModelDetails-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-gui-install_subtargets sub-RankPointGenerator-install_subtargets sub-ModelDetails-install_subtargets FORCE
uninstall_subtargets: sub-gui-uninstall_subtargets sub-RankPointGenerator-uninstall_subtargets sub-ModelDetails-uninstall_subtargets FORCE

sub-gui-check:
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/gui/gui.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-RankPointGenerator-check:
	@test -d RankPointGenerator/ || mkdir -p RankPointGenerator/
	cd RankPointGenerator/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/RankPointGenerator/RankPointGenerator.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ModelDetails-check:
	@test -d ModelDetails/ || mkdir -p ModelDetails/
	cd ModelDetails/ && ( test -e Makefile || $(QMAKE) /Users/arkygeek/QtProjects/DataRanking/ModelDetails/ModelDetails.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-gui-check sub-RankPointGenerator-check sub-ModelDetails-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

